/**
 * The parts of org.springframework.web.util.UriComponentsBuilder / HierarchicalUriComponents that the ported
 * conditions use: `fromUriString(uri).queryParam(name, value)...toUriString()`.
 *
 * `toUriString()` percent-encodes (UTF-8) every URI component except for the characters that are allowed in that
 * component (RFC 3986 character classes), so e.g. a '%' in the original uri is encoded again as %25 and a space
 * in a query parameter value becomes %20.
 *
 * UPSTREAM DEVIATION: Spring treats '+' as an allowed sub-delimiter in query parameters and leaves it as is,
 * but every form-decoding server (Spring/Tomcat, Apache httpclient's URLEncodedUtils, Node's URLSearchParams)
 * turns a literal '+' back into a space. A client_id generated by the suite's own RP tests
 * (RFC6749AppendixASyntaxUtils) can contain '+', which breaks suite-vs-suite runs, so '+' is encoded as %2B
 * here. A conformant server decodes %2B to '+', so the decoded parameter values are the same as upstream's.
 */

export function isUnreserved(c: string): boolean {
	return /^[A-Za-z0-9\-._~]$/.test(c);
}

export function isSubDelimiter(c: string): boolean {
	return "!$&'()*+,;=".includes(c);
}

export function isPchar(c: string): boolean {
	return isUnreserved(c) || isSubDelimiter(c) || c === ":" || c === "@";
}

/** HierarchicalUriComponents.Type.QUERY_PARAM.isAllowed, minus '+' (see the note above) */
export function isQueryParamChar(c: string): boolean {
	return c !== "=" && c !== "&" && c !== "+" && (isPchar(c) || c === "/" || c === "?");
}

export function encodeUriComponent(source: string, allowed: (c: string) => boolean): string {
	let out = "";
	for (const c of source) {
		if (c.length === 1 && c.charCodeAt(0) < 0x80 && allowed(c)) {
			out += c;
		} else {
			for (const b of Buffer.from(c, "utf8")) {
				out += "%" + b.toString(16).toUpperCase().padStart(2, "0");
			}
		}
	}
	return out;
}

/** Percent-encodes a query parameter name or value (HierarchicalUriComponents.Type.QUERY_PARAM) */
export function encodeQueryParam(s: string): string {
	return encodeUriComponent(s, isQueryParamChar);
}

// UriComponentsBuilder.URI_PATTERN
const URI_PATTERN =
	/^(([^:/?#]+):)?(\/\/(([^@[/?#]*)@)?(\[[0-9a-fA-F:.]*[%A-Za-z0-9]*\]|[^[/?#:]*)(:(\d*(?:\{[^/]+?\})?))?)?([^?#]*)(\?([^#]*))?(#(.*))?$/s;
const QUERY_PARAM_PATTERN = /([^&=]+)(=?)([^&]+)?/g;

/**
 * UriComponentsBuilder.fromUriString(uri).queryParam(name, value)...toUriString(): the given parameters are
 * appended to the uri's existing query and every component is encoded.
 */
export function toUriString(uri: string, queryParam: [string, string | null][]): string {
	const matcher = URI_PATTERN.exec(uri);
	if (matcher === null) {
		throw new Error("[" + uri + "] is not a valid URI");
	}
	const scheme = matcher[2];
	const userInfo = matcher[5];
	const host = matcher[6];
	const port = matcher[8];
	const path = matcher[9];
	const query = matcher[11];
	const fragment = matcher[13];

	let opaque = false;
	if (scheme) {
		const rest = uri.substring(scheme.length);
		if (!rest.startsWith(":/")) {
			opaque = true;
		}
	}

	if (opaque) {
		// an opaque uri has no query component, the added parameters are dropped
		let ssp = uri.substring(scheme.length + 1);
		if (fragment) {
			ssp = ssp.substring(0, ssp.length - (fragment.length + 1));
		}
		return scheme + ":" + ssp + (fragment && fragment.trim() ? "#" + fragment : "");
	}

	const queryParams: [string, string | null][] = [];
	if (query) {
		for (const m of query.matchAll(QUERY_PARAM_PATTERN)) {
			queryParams.push([m[1], m[3] !== undefined ? m[3] : m[2] ? "" : null]);
		}
	}
	for (const [name, value] of queryParam) {
		queryParams.push([name, value]);
	}

	let out = "";
	if (scheme) {
		out += scheme + ":";
	}
	if (userInfo != null || host != null) {
		out += "//";
		if (userInfo != null) {
			out += encodeUriComponent(userInfo, (c) => isUnreserved(c) || isSubDelimiter(c) || c === ":") + "@";
		}
		if (host != null) {
			out += host.startsWith("[") ? host : encodeUriComponent(host, (c) => isUnreserved(c) || isSubDelimiter(c));
		}
		if (port) {
			out += ":" + port;
		}
	}
	const encodedPath = encodeUriComponent(path ?? "", (c) => isPchar(c) || c === "/");
	if (encodedPath.length > 0) {
		if (out.length !== 0 && !encodedPath.startsWith("/")) {
			out += "/";
		}
		out += encodedPath;
	}
	if (queryParams.length > 0) {
		out +=
			"?" +
			queryParams
				.map(([name, value]) => {
					const n = encodeQueryParam(name);
					return value !== null ? n + "=" + encodeQueryParam(value) : n;
				})
				.join("&");
	}
	if (fragment && fragment.trim()) {
		out += "#" + encodeUriComponent(fragment, (c) => isPchar(c) || c === "/" || c === "?");
	}
	return out;
}
