#!/usr/bin/env node
/**
 * Generates src/registry.ts: imports every test module (class with `static ... meta: PublishTestModule`) and
 * test plan (`static ... meta: PublishTestPlan`) under src/openid and exports lookup tables.
 *
 *   node scripts/gen-registry.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const srcDir = join(root, "src", "openid");

const files = readdirSync(srcDir, { recursive: true, encoding: "utf8" })
	.filter((name) => name.endsWith(".ts") && !name.endsWith(".test.ts"))
	.map((name) => join(srcDir, name))
	.sort();

const modules: { cls: string; file: string; testName: string }[] = [];
const plans: { cls: string; file: string; planName: string }[] = [];

for (const file of files) {
	const text = readFileSync(file, "utf8");
	for (const m of text.matchAll(
		/export\s+class\s+(\w+)\s+extends[\s\S]*?static\s+(?:override\s+)?(?:readonly\s+)?meta\s*:\s*(PublishTestModule|PublishTestPlan)\s*=\s*\{([\s\S]*?)\n\t\};/g,
	)) {
		const [, cls, kind, body] = m;
		if (kind === "PublishTestModule") {
			const name = /testName:\s*"([^"]+)"/.exec(body)?.[1];
			if (name) {
				modules.push({ cls, file, testName: name });
			}
		} else {
			const name = /testPlanName:\s*"([^"]+)"/.exec(body)?.[1];
			if (name) {
				plans.push({ cls, file, planName: name });
			}
		}
	}
}

const rel = (f: string) => "./" + relative(join(root, "src"), f).replaceAll("\\", "/");
const lines = [
	"// GENERATED by scripts/gen-registry.ts - do not edit by hand. Re-run: node scripts/gen-registry.ts",
	'import type { AbstractTestModule } from "./framework/AbstractTestModule.ts";',
	'import type { TestPlanClass } from "./framework/plan.ts";',
	'import type { TestModuleClass } from "./framework/TestModule.ts";',
	...[...modules, ...plans].map((x) => `import { ${x.cls} } from "${rel(x.file)}";`),
	"",
	"export const modules: TestModuleClass<AbstractTestModule>[] = [",
	...modules.map((m) => `\t${m.cls}, // ${m.testName}`),
	"];",
	"",
	"export const plans: TestPlanClass[] = [",
	...plans.map((p) => `\t${p.cls}, // ${p.planName}`),
	"];",
	"",
	`export function findModule(testName: string): TestModuleClass<AbstractTestModule> | undefined {
	return modules.find((m) => m.meta?.testName === testName);
}

export function findPlan(testPlanName: string): TestPlanClass | undefined {
	return plans.find((p) => p.meta.testPlanName === testPlanName);
}
`,
];
writeFileSync(join(root, "src", "registry.ts"), lines.join("\n"));
console.log(`registry: ${modules.length} modules, ${plans.length} plans`);
