// GENERATED by scripts/gen-registry.ts - do not edit by hand. Re-run: node scripts/gen-registry.ts
import type { AbstractTestModule } from "./framework/AbstractTestModule.ts";
import type { TestPlanClass } from "./framework/plan.ts";
import type { TestModuleClass } from "./framework/TestModule.ts";

export const modules: TestModuleClass<AbstractTestModule>[] = [];

export const plans: TestPlanClass[] = [];

export function findModule(testName: string): TestModuleClass<AbstractTestModule> | undefined {
	return modules.find((m) => m.meta?.testName === testName);
}

export function findPlan(testPlanName: string): TestPlanClass | undefined {
	return plans.find((p) => p.meta.testPlanName === testPlanName);
}
