// GENERATED by scripts/gen-registry.ts - do not edit by hand. Re-run: node scripts/gen-registry.ts
import type { AbstractTestModule } from "./framework/AbstractTestModule.ts";
import type { TestPlanClass } from "./framework/plan.ts";
import type { TestModuleClass } from "./framework/TestModule.ts";
import { OIDCC3rdPartyInitLogin } from "./openid/OIDCC3rdPartyInitLogin.ts";
import { OIDCC3rdPartyInitLoginNonHttps } from "./openid/OIDCC3rdPartyInitLoginNonHttps.ts";
import { OIDCCAlternateHappyFlow } from "./openid/OIDCCAlternateHappyFlow.ts";
import { OIDCCAuthCodeReuse } from "./openid/OIDCCAuthCodeReuse.ts";
import { OIDCCAuthCodeReuseAfter30Seconds } from "./openid/OIDCCAuthCodeReuseAfter30Seconds.ts";
import { OIDCCBackChannelRpInitiatedLogout } from "./openid/OIDCCBackChannelRpInitiatedLogout.ts";
import { OIDCCBackchannelLogoutDiscoveryEndpointVerification } from "./openid/OIDCCBackchannelLogoutDiscoveryEndpointVerification.ts";
import { OIDCCClaimsEssential } from "./openid/OIDCCClaimsEssential.ts";
import { OIDCCClaimsLocales } from "./openid/OIDCCClaimsLocales.ts";
import { OIDCCDiscoveryEndpointVerification } from "./openid/OIDCCDiscoveryEndpointVerification.ts";
import { OIDCCDisplayPage } from "./openid/OIDCCDisplayPage.ts";
import { OIDCCDisplayPopup } from "./openid/OIDCCDisplayPopup.ts";
import { OIDCCEnsureClientAssertionWithIssAudSucceeds } from "./openid/OIDCCEnsureClientAssertionWithIssAudSucceeds.ts";
import { OIDCCEnsurePostRequestSucceeds } from "./openid/OIDCCEnsurePostRequestSucceeds.ts";
import { OIDCCEnsureRedirectUriInAuthorizationRequest } from "./openid/OIDCCEnsureRedirectUriInAuthorizationRequest.ts";
import { OIDCCEnsureRegisteredRedirectUri } from "./openid/OIDCCEnsureRegisteredRedirectUri.ts";
import { OIDCCEnsureRequestObjectWithRedirectUri } from "./openid/OIDCCEnsureRequestObjectWithRedirectUri.ts";
import { OIDCCEnsureRequestWithAcrValuesSucceeds } from "./openid/OIDCCEnsureRequestWithAcrValuesSucceeds.ts";
import { OIDCCEnsureRequestWithUnknownParameterSucceeds } from "./openid/OIDCCEnsureRequestWithUnknownParameterSucceeds.ts";
import { OIDCCEnsureRequestWithValidPkceSucceeds } from "./openid/OIDCCEnsureRequestWithValidPkceSucceeds.ts";
import { OIDCCEnsureRequestWithoutNonceSucceedsForCodeFlow } from "./openid/OIDCCEnsureRequestWithoutNonceSucceedsForCodeFlow.ts";
import { OIDCCFrontChannelRpInitiatedLogout } from "./openid/OIDCCFrontChannelRpInitiatedLogout.ts";
import { OIDCCFrontchannelLogoutDiscoveryEndpointVerification } from "./openid/OIDCCFrontchannelLogoutDiscoveryEndpointVerification.ts";
import { OIDCCIdTokenHint } from "./openid/OIDCCIdTokenHint.ts";
import { OIDCCIdTokenRS256 } from "./openid/OIDCCIdTokenRS256.ts";
import { OIDCCIdTokenSignature } from "./openid/OIDCCIdTokenSignature.ts";
import { OIDCCIdTokenUnsigned } from "./openid/OIDCCIdTokenUnsigned.ts";
import { OIDCCLoginHint } from "./openid/OIDCCLoginHint.ts";
import { OIDCCMaxAge1 } from "./openid/OIDCCMaxAge1.ts";
import { OIDCCMaxAge10000 } from "./openid/OIDCCMaxAge10000.ts";
import { OIDCCPromptLogin } from "./openid/OIDCCPromptLogin.ts";
import { OIDCCPromptNoneLoggedIn } from "./openid/OIDCCPromptNoneLoggedIn.ts";
import { OIDCCPromptNoneNotLoggedIn } from "./openid/OIDCCPromptNoneNotLoggedIn.ts";
import { OIDCCRedirectUriQueryAdded } from "./openid/OIDCCRedirectUriQueryAdded.ts";
import { OIDCCRedirectUriQueryMismatch } from "./openid/OIDCCRedirectUriQueryMismatch.ts";
import { OIDCCRedirectUriQueryOK } from "./openid/OIDCCRedirectUriQueryOK.ts";
import { OIDCCRedirectUriRegFrag } from "./openid/OIDCCRedirectUriRegFrag.ts";
import { OIDCCRefreshToken } from "./openid/OIDCCRefreshToken.ts";
import { OIDCCRefreshTokenRPKeyRotation } from "./openid/OIDCCRefreshTokenRPKeyRotation.ts";
import { OIDCCRegistrationJwksUri } from "./openid/OIDCCRegistrationJwksUri.ts";
import { OIDCCRegistrationLogoUri } from "./openid/OIDCCRegistrationLogoUri.ts";
import { OIDCCRegistrationPolicyUri } from "./openid/OIDCCRegistrationPolicyUri.ts";
import { OIDCCRegistrationSectorBad } from "./openid/OIDCCRegistrationSectorBad.ts";
import { OIDCCRegistrationSectorUri } from "./openid/OIDCCRegistrationSectorUri.ts";
import { OIDCCRegistrationTosUri } from "./openid/OIDCCRegistrationTosUri.ts";
import { OIDCCRequestUriSignedRS256 } from "./openid/OIDCCRequestUriSignedRS256.ts";
import { OIDCCRequestUriUnsigned } from "./openid/OIDCCRequestUriUnsigned.ts";
import { OIDCCRequestUriUnsignedSupportedCorrectlyOrRejectedAsUnsupported } from "./openid/OIDCCRequestUriUnsignedSupportedCorrectlyOrRejectedAsUnsupported.ts";
import { OIDCCResponseTypeMissing } from "./openid/OIDCCResponseTypeMissing.ts";
import { OIDCCRpInitiatedLogout } from "./openid/OIDCCRpInitiatedLogout.ts";
import { OIDCCRpInitiatedLogoutBadIdTokenHint } from "./openid/OIDCCRpInitiatedLogoutBadIdTokenHint.ts";
import { OIDCCRpInitiatedLogoutBadLogoutRedirectUri } from "./openid/OIDCCRpInitiatedLogoutBadLogoutRedirectUri.ts";
import { OIDCCRpInitiatedLogoutDiscoveryEndpointVerification } from "./openid/OIDCCRpInitiatedLogoutDiscoveryEndpointVerification.ts";
import { OIDCCRpInitiatedLogoutModifiedIdTokenHint } from "./openid/OIDCCRpInitiatedLogoutModifiedIdTokenHint.ts";
import { OIDCCRpInitiatedLogoutNoIdTokenHint } from "./openid/OIDCCRpInitiatedLogoutNoIdTokenHint.ts";
import { OIDCCRpInitiatedLogoutNoParams } from "./openid/OIDCCRpInitiatedLogoutNoParams.ts";
import { OIDCCRpInitiatedLogoutNoPostLogoutRedirectUri } from "./openid/OIDCCRpInitiatedLogoutNoPostLogoutRedirectUri.ts";
import { OIDCCRpInitiatedLogoutNoState } from "./openid/OIDCCRpInitiatedLogoutNoState.ts";
import { OIDCCRpInitiatedLogoutOnlyState } from "./openid/OIDCCRpInitiatedLogoutOnlyState.ts";
import { OIDCCRpInitiatedLogoutQueryAddedToLogoutRedirectUri } from "./openid/OIDCCRpInitiatedLogoutQueryAddedToLogoutRedirectUri.ts";
import { OIDCCScopeAddress } from "./openid/OIDCCScopeAddress.ts";
import { OIDCCScopeAll } from "./openid/OIDCCScopeAll.ts";
import { OIDCCScopeEmail } from "./openid/OIDCCScopeEmail.ts";
import { OIDCCScopePhone } from "./openid/OIDCCScopePhone.ts";
import { OIDCCScopeProfile } from "./openid/OIDCCScopeProfile.ts";
import { OIDCCServerRotateKeys } from "./openid/OIDCCServerRotateKeys.ts";
import { OIDCCServerTest } from "./openid/OIDCCServerTest.ts";
import { OIDCCServerTestClientSecretPost } from "./openid/OIDCCServerTestClientSecretPost.ts";
import { OIDCCSessionManagementDiscoveryEndpointVerification } from "./openid/OIDCCSessionManagementDiscoveryEndpointVerification.ts";
import { OIDCCSessionManagementRpInitiatedLogout } from "./openid/OIDCCSessionManagementRpInitiatedLogout.ts";
import { OIDCCUiLocales } from "./openid/OIDCCUiLocales.ts";
import { OIDCCUnsignedRequestObjectSupportedCorrectlyOrRejectedAsUnsupported } from "./openid/OIDCCUnsignedRequestObjectSupportedCorrectlyOrRejectedAsUnsupported.ts";
import { OIDCCUserInfoGet } from "./openid/OIDCCUserInfoGet.ts";
import { OIDCCUserInfoPostBody } from "./openid/OIDCCUserInfoPostBody.ts";
import { OIDCCUserInfoPostHeader } from "./openid/OIDCCUserInfoPostHeader.ts";
import { OIDCCUserInfoRS256 } from "./openid/OIDCCUserInfoRS256.ts";
import { OIDCCClient3rdPartyInitiatedLoginTest } from "./openid/client/OIDCCClient3rdPartyInitiatedLoginTest.ts";
import { OIDCCClientTest } from "./openid/client/OIDCCClientTest.ts";
import { OIDCCClientTestClientSecretBasic } from "./openid/client/OIDCCClientTestClientSecretBasic.ts";
import { OIDCCClientTestFormPostError } from "./openid/client/OIDCCClientTestFormPostError.ts";
import { OIDCCClientTestIdTokenSigAlgNone } from "./openid/client/OIDCCClientTestIdTokenSigAlgNone.ts";
import { OIDCCClientTestIdTokenSignedUsingRS256 } from "./openid/client/OIDCCClientTestIdTokenSignedUsingRS256.ts";
import { OIDCCClientTestInvalidAudInIdToken } from "./openid/client/OIDCCClientTestInvalidAudInIdToken.ts";
import { OIDCCClientTestInvalidIdTokenSignatureWithRS256 } from "./openid/client/OIDCCClientTestInvalidIdTokenSignatureWithRS256.ts";
import { OIDCCClientTestInvalidIssuerInIdToken } from "./openid/client/OIDCCClientTestInvalidIssuerInIdToken.ts";
import { OIDCCClientTestInvalidSubInUserinfoResponse } from "./openid/client/OIDCCClientTestInvalidSubInUserinfoResponse.ts";
import { OIDCCClientTestKidAbsentMultipleMatchingKeysInJwks } from "./openid/client/OIDCCClientTestKidAbsentMultipleMatchingKeysInJwks.ts";
import { OIDCCClientTestKidAbsentSingleJwks } from "./openid/client/OIDCCClientTestKidAbsentSingleJwks.ts";
import { OIDCCClientTestMissingIatInIdToken } from "./openid/client/OIDCCClientTestMissingIatInIdToken.ts";
import { OIDCCClientTestMissingSubInIdToken } from "./openid/client/OIDCCClientTestMissingSubInIdToken.ts";
import { OIDCCClientTestNonceInvalid } from "./openid/client/OIDCCClientTestNonceInvalid.ts";
import { OIDCCClientTestRequestUriSignedWithNone } from "./openid/client/OIDCCClientTestRequestUriSignedWithNone.ts";
import { OIDCCClientTestRequestUriSignedWithRS256 } from "./openid/client/OIDCCClientTestRequestUriSignedWithRS256.ts";
import { OIDCCClientTestScopeUserInfoClaims } from "./openid/client/OIDCCClientTestScopeUserInfoClaims.ts";
import { OIDCCClientTestSignedUserinfo } from "./openid/client/OIDCCClientTestSignedUserinfo.ts";
import { OIDCCClientTestUserinfoBearerBody } from "./openid/client/OIDCCClientTestUserinfoBearerBody.ts";
import { OIDCCClientTestUserinfoBearerHeader } from "./openid/client/OIDCCClientTestUserinfoBearerHeader.ts";
import { OIDCCClientTestDiscoveryIssuerMismatch } from "./openid/client/config/OIDCCClientTestDiscoveryIssuerMismatch.ts";
import { OIDCCClientTestDiscoveryJwksUriKeys } from "./openid/client/config/OIDCCClientTestDiscoveryJwksUriKeys.ts";
import { OIDCCClientTestDiscoveryOpenIDConfiguration } from "./openid/client/config/OIDCCClientTestDiscoveryOpenIDConfiguration.ts";
import { OIDCCClientTestDiscoveryWebfingerAcct } from "./openid/client/config/OIDCCClientTestDiscoveryWebfingerAcct.ts";
import { OIDCCClientTestDiscoveryWebfingerURL } from "./openid/client/config/OIDCCClientTestDiscoveryWebfingerURL.ts";
import { OIDCCClientTestDynamicRegistration } from "./openid/client/config/OIDCCClientTestDynamicRegistration.ts";
import { OIDCCClientTestSigningKeyRotation } from "./openid/client/config/OIDCCClientTestSigningKeyRotation.ts";
import { OIDCCClientTestSigningKeyRotationJustBeforeSigning } from "./openid/client/config/OIDCCClientTestSigningKeyRotationJustBeforeSigning.ts";
import { OIDCCClientTestBackChannelLogout } from "./openid/client/logout/OIDCCClientTestBackChannelLogout.ts";
import { OIDCCClientTestBackChannelLogoutAlgNone } from "./openid/client/logout/OIDCCClientTestBackChannelLogoutAlgNone.ts";
import { OIDCCClientTestBackChannelLogoutNoEvent } from "./openid/client/logout/OIDCCClientTestBackChannelLogoutNoEvent.ts";
import { OIDCCClientTestBackChannelLogoutWithNonce } from "./openid/client/logout/OIDCCClientTestBackChannelLogoutWithNonce.ts";
import { OIDCCClientTestBackChannelLogoutWrongAlg } from "./openid/client/logout/OIDCCClientTestBackChannelLogoutWrongAlg.ts";
import { OIDCCClientTestBackChannelLogoutWrongAud } from "./openid/client/logout/OIDCCClientTestBackChannelLogoutWrongAud.ts";
import { OIDCCClientTestBackChannelLogoutWrongEvent } from "./openid/client/logout/OIDCCClientTestBackChannelLogoutWrongEvent.ts";
import { OIDCCClientTestBackChannelLogoutWrongIssuer } from "./openid/client/logout/OIDCCClientTestBackChannelLogoutWrongIssuer.ts";
import { OIDCCClientTestFrontChannelLogoutOPInitiated } from "./openid/client/logout/OIDCCClientTestFrontChannelLogoutOPInitiated.ts";
import { OIDCCClientTestFrontChannelLogoutRPInitiated } from "./openid/client/logout/OIDCCClientTestFrontChannelLogoutRPInitiated.ts";
import { OIDCCClientTestRPInitLogout } from "./openid/client/logout/OIDCCClientTestRPInitLogout.ts";
import { OIDCCClientTestRPInitLogoutInvalidState } from "./openid/client/logout/OIDCCClientTestRPInitLogoutInvalidState.ts";
import { OIDCCClientTestRPInitLogoutNoState } from "./openid/client/logout/OIDCCClientTestRPInitLogoutNoState.ts";
import { OIDCCClientTestSessionManagement } from "./openid/client/logout/OIDCCClientTestSessionManagement.ts";
import { OIDCC3rdPartyInitLoginTestPlan } from "./openid/OIDCC3rdPartyInitLoginTestPlan.ts";
import { OIDCCBackchannelRpInitiatedLogoutTestPlan } from "./openid/OIDCCBackchannelRpInitiatedLogoutTestPlan.ts";
import { OIDCCBasicTestPlan } from "./openid/OIDCCBasicTestPlan.ts";
import { OIDCCConfigTestPlan } from "./openid/OIDCCConfigTestPlan.ts";
import { OIDCCDynamicTestPlan } from "./openid/OIDCCDynamicTestPlan.ts";
import { OIDCCFrontchannelRpInitiatedLogoutTestPlan } from "./openid/OIDCCFrontchannelRpInitiatedLogoutTestPlan.ts";
import { OIDCCRpInitiatedLogoutTestPlan } from "./openid/OIDCCRpInitiatedLogoutTestPlan.ts";
import { OIDCCSessionManagementTestPlan } from "./openid/OIDCCSessionManagementTestPlan.ts";
import { OIDCCClient3rdPartyInitiatedLoginTestPlan } from "./openid/client/OIDCCClient3rdPartyInitiatedLoginTestPlan.ts";
import { OIDCCClientBasicTestPlan } from "./openid/client/OIDCCClientBasicTestPlan.ts";
import { OIDCCClientDynamicTestPlan } from "./openid/client/OIDCCClientDynamicTestPlan.ts";
import { OIDCCClientBackChannelLogoutRPBasicTestPlan } from "./openid/client/logout/plan/OIDCCClientBackChannelLogoutRPBasicTestPlan.ts";
import { OIDCCClientFrontChannelLogoutRPBasicTestPlan } from "./openid/client/logout/plan/OIDCCClientFrontChannelLogoutRPBasicTestPlan.ts";
import { OIDCCClientLogoutTestPlan } from "./openid/client/logout/plan/OIDCCClientLogoutTestPlan.ts";
import { OIDCCClientRPInitiatedLogoutRPBasicTestPlan } from "./openid/client/logout/plan/OIDCCClientRPInitiatedLogoutRPBasicTestPlan.ts";
import { OIDCCClientSessionManagementRPBasicTestPlan } from "./openid/client/logout/plan/OIDCCClientSessionManagementRPBasicTestPlan.ts";

export const modules: TestModuleClass<AbstractTestModule>[] = [
	OIDCC3rdPartyInitLogin, // oidcc-3rd_party-init-login
	OIDCC3rdPartyInitLoginNonHttps, // oidcc-3rd_party-init-login-nohttps
	OIDCCAlternateHappyFlow, // oidcc-alternate-happy-flow
	OIDCCAuthCodeReuse, // oidcc-codereuse
	OIDCCAuthCodeReuseAfter30Seconds, // oidcc-codereuse-30seconds
	OIDCCBackChannelRpInitiatedLogout, // oidcc-backchannel-rp-initiated-logout
	OIDCCBackchannelLogoutDiscoveryEndpointVerification, // oidcc-backchannel-logout-discovery-endpoint-verification
	OIDCCClaimsEssential, // oidcc-claims-essential
	OIDCCClaimsLocales, // oidcc-claims-locales
	OIDCCDiscoveryEndpointVerification, // oidcc-discovery-endpoint-verification
	OIDCCDisplayPage, // oidcc-display-page
	OIDCCDisplayPopup, // oidcc-display-popup
	OIDCCEnsureClientAssertionWithIssAudSucceeds, // oidcc-ensure-client-assertion-with-iss-aud-succeeds
	OIDCCEnsurePostRequestSucceeds, // oidcc-ensure-post-request-succeeds
	OIDCCEnsureRedirectUriInAuthorizationRequest, // oidcc-ensure-redirect-uri-in-authorization-request
	OIDCCEnsureRegisteredRedirectUri, // oidcc-ensure-registered-redirect-uri
	OIDCCEnsureRequestObjectWithRedirectUri, // oidcc-ensure-request-object-with-redirect-uri
	OIDCCEnsureRequestWithAcrValuesSucceeds, // oidcc-ensure-request-with-acr-values-succeeds
	OIDCCEnsureRequestWithUnknownParameterSucceeds, // oidcc-ensure-request-with-unknown-parameter-succeeds
	OIDCCEnsureRequestWithValidPkceSucceeds, // oidcc-ensure-request-with-valid-pkce-succeeds
	OIDCCEnsureRequestWithoutNonceSucceedsForCodeFlow, // oidcc-ensure-request-without-nonce-succeeds-for-code-flow
	OIDCCFrontChannelRpInitiatedLogout, // oidcc-frontchannel-rp-initiated-logout
	OIDCCFrontchannelLogoutDiscoveryEndpointVerification, // oidcc-frontchannel-logout-discovery-endpoint-verification
	OIDCCIdTokenHint, // oidcc-id-token-hint
	OIDCCIdTokenRS256, // oidcc-idtoken-rs256
	OIDCCIdTokenSignature, // oidcc-idtoken-signature
	OIDCCIdTokenUnsigned, // oidcc-idtoken-unsigned
	OIDCCLoginHint, // oidcc-login-hint
	OIDCCMaxAge1, // oidcc-max-age-1
	OIDCCMaxAge10000, // oidcc-max-age-10000
	OIDCCPromptLogin, // oidcc-prompt-login
	OIDCCPromptNoneLoggedIn, // oidcc-prompt-none-logged-in
	OIDCCPromptNoneNotLoggedIn, // oidcc-prompt-none-not-logged-in
	OIDCCRedirectUriQueryAdded, // oidcc-redirect-uri-query-added
	OIDCCRedirectUriQueryMismatch, // oidcc-redirect-uri-query-mismatch
	OIDCCRedirectUriQueryOK, // oidcc-redirect-uri-query-OK
	OIDCCRedirectUriRegFrag, // oidcc-redirect-uri-regfrag
	OIDCCRefreshToken, // oidcc-refresh-token
	OIDCCRefreshTokenRPKeyRotation, // oidcc-refresh-token-rp-key-rotation
	OIDCCRegistrationJwksUri, // oidcc-registration-jwks-uri
	OIDCCRegistrationLogoUri, // oidcc-registration-logo-uri
	OIDCCRegistrationPolicyUri, // oidcc-registration-policy-uri
	OIDCCRegistrationSectorBad, // oidcc-registration-sector-bad
	OIDCCRegistrationSectorUri, // oidcc-registration-sector-uri
	OIDCCRegistrationTosUri, // oidcc-registration-tos-uri
	OIDCCRequestUriSignedRS256, // oidcc-request-uri-signed-rs256
	OIDCCRequestUriUnsigned, // oidcc-request-uri-unsigned
	OIDCCRequestUriUnsignedSupportedCorrectlyOrRejectedAsUnsupported, // oidcc-request-uri-unsigned-supported-correctly-or-rejected-as-unsupported
	OIDCCResponseTypeMissing, // oidcc-response-type-missing
	OIDCCRpInitiatedLogout, // oidcc-rp-initiated-logout
	OIDCCRpInitiatedLogoutBadIdTokenHint, // oidcc-rp-initiated-logout-bad-id-token-hint
	OIDCCRpInitiatedLogoutBadLogoutRedirectUri, // oidcc-rp-initiated-logout-bad-post-logout-redirect-uri
	OIDCCRpInitiatedLogoutDiscoveryEndpointVerification, // oidcc-rp-initiated-logout-discovery-endpoint-verification
	OIDCCRpInitiatedLogoutModifiedIdTokenHint, // oidcc-rp-initiated-logout-modified-id-token-hint
	OIDCCRpInitiatedLogoutNoIdTokenHint, // oidcc-rp-initiated-logout-no-id-token-hint
	OIDCCRpInitiatedLogoutNoParams, // oidcc-rp-initiated-logout-no-params
	OIDCCRpInitiatedLogoutNoPostLogoutRedirectUri, // oidcc-rp-initiated-logout-no-post-logout-redirect-uri
	OIDCCRpInitiatedLogoutNoState, // oidcc-rp-initiated-logout-no-state
	OIDCCRpInitiatedLogoutOnlyState, // oidcc-rp-initiated-logout-only-state
	OIDCCRpInitiatedLogoutQueryAddedToLogoutRedirectUri, // oidcc-rp-initiated-logout-query-added-to-post-logout-redirect-uri
	OIDCCScopeAddress, // oidcc-scope-address
	OIDCCScopeAll, // oidcc-scope-all
	OIDCCScopeEmail, // oidcc-scope-email
	OIDCCScopePhone, // oidcc-scope-phone
	OIDCCScopeProfile, // oidcc-scope-profile
	OIDCCServerRotateKeys, // oidcc-server-rotate-keys
	OIDCCServerTest, // oidcc-server
	OIDCCServerTestClientSecretPost, // oidcc-server-client-secret-post
	OIDCCSessionManagementDiscoveryEndpointVerification, // oidcc-session-management-discovery-endpoint-verification
	OIDCCSessionManagementRpInitiatedLogout, // oidcc-session-management-rp-initiated-logout
	OIDCCUiLocales, // oidcc-ui-locales
	OIDCCUnsignedRequestObjectSupportedCorrectlyOrRejectedAsUnsupported, // oidcc-unsigned-request-object-supported-correctly-or-rejected-as-unsupported
	OIDCCUserInfoGet, // oidcc-userinfo-get
	OIDCCUserInfoPostBody, // oidcc-userinfo-post-body
	OIDCCUserInfoPostHeader, // oidcc-userinfo-post-header
	OIDCCUserInfoRS256, // oidcc-userinfo-rs256
	OIDCCClient3rdPartyInitiatedLoginTest, // oidcc-client-test-3rd-party-init-login
	OIDCCClientTest, // oidcc-client-test
	OIDCCClientTestClientSecretBasic, // oidcc-client-test-client-secret-basic
	OIDCCClientTestFormPostError, // oidcc-client-test-form-post-error
	OIDCCClientTestIdTokenSigAlgNone, // oidcc-client-test-idtoken-sig-none
	OIDCCClientTestIdTokenSignedUsingRS256, // oidcc-client-test-idtoken-sig-rs256
	OIDCCClientTestInvalidAudInIdToken, // oidcc-client-test-invalid-aud
	OIDCCClientTestInvalidIdTokenSignatureWithRS256, // oidcc-client-test-invalid-sig-rs256
	OIDCCClientTestInvalidIssuerInIdToken, // oidcc-client-test-invalid-iss
	OIDCCClientTestInvalidSubInUserinfoResponse, // oidcc-client-test-userinfo-invalid-sub
	OIDCCClientTestKidAbsentMultipleMatchingKeysInJwks, // oidcc-client-test-kid-absent-multiple-jwks
	OIDCCClientTestKidAbsentSingleJwks, // oidcc-client-test-kid-absent-single-jwks
	OIDCCClientTestMissingIatInIdToken, // oidcc-client-test-missing-iat
	OIDCCClientTestMissingSubInIdToken, // oidcc-client-test-missing-sub
	OIDCCClientTestNonceInvalid, // oidcc-client-test-nonce-invalid
	OIDCCClientTestRequestUriSignedWithNone, // oidcc-client-test-request-uri-signed-none
	OIDCCClientTestRequestUriSignedWithRS256, // oidcc-client-test-request-uri-signed-rs256
	OIDCCClientTestScopeUserInfoClaims, // oidcc-client-test-scope-userinfo-claims
	OIDCCClientTestSignedUserinfo, // oidcc-client-test-userinfo-signed
	OIDCCClientTestUserinfoBearerBody, // oidcc-client-test-userinfo-bearer-body
	OIDCCClientTestUserinfoBearerHeader, // oidcc-client-test-userinfo-bearer-header
	OIDCCClientTestDiscoveryIssuerMismatch, // oidcc-client-test-discovery-issuer-mismatch
	OIDCCClientTestDiscoveryJwksUriKeys, // oidcc-client-test-discovery-jwks-uri-keys
	OIDCCClientTestDiscoveryOpenIDConfiguration, // oidcc-client-test-discovery-openid-config
	OIDCCClientTestDiscoveryWebfingerAcct, // oidcc-client-test-discovery-webfinger-acct
	OIDCCClientTestDiscoveryWebfingerURL, // oidcc-client-test-discovery-webfinger-url
	OIDCCClientTestDynamicRegistration, // oidcc-client-test-dynamic-registration
	OIDCCClientTestSigningKeyRotation, // oidcc-client-test-signing-key-rotation
	OIDCCClientTestSigningKeyRotationJustBeforeSigning, // oidcc-client-test-signing-key-rotation-just-before-signing
	OIDCCClientTestBackChannelLogout, // oidcc-client-test-rp-backchannel-rpinitlogout
	OIDCCClientTestBackChannelLogoutAlgNone, // oidcc-client-test-rp-backchannel-rpinitlogout-alg-none
	OIDCCClientTestBackChannelLogoutNoEvent, // oidcc-client-test-rp-backchannel-rpinitlogout-no-event
	OIDCCClientTestBackChannelLogoutWithNonce, // oidcc-client-test-rp-backchannel-rpinitlogout-with-nonce
	OIDCCClientTestBackChannelLogoutWrongAlg, // oidcc-client-test-rp-backchannel-rpinitlogout-wrong-alg
	OIDCCClientTestBackChannelLogoutWrongAud, // oidcc-client-test-rp-backchannel-rpinitlogout-wrong-aud
	OIDCCClientTestBackChannelLogoutWrongEvent, // oidcc-client-test-rp-backchannel-rpinitlogout-wrong-event
	OIDCCClientTestBackChannelLogoutWrongIssuer, // oidcc-client-test-rp-backchannel-rpinitlogout-wrong-iss
	OIDCCClientTestFrontChannelLogoutOPInitiated, // oidcc-client-test-rp-frontchannel-opinitlogout
	OIDCCClientTestFrontChannelLogoutRPInitiated, // oidcc-client-test-rp-frontchannel-rpinitlogout
	OIDCCClientTestRPInitLogout, // oidcc-client-test-rp-init-logout
	OIDCCClientTestRPInitLogoutInvalidState, // oidcc-client-test-rp-init-logout-other-state
	OIDCCClientTestRPInitLogoutNoState, // oidcc-client-test-rp-init-logout-no-state
	OIDCCClientTestSessionManagement, // oidcc-client-test-session-management
];

export const plans: TestPlanClass[] = [
	OIDCC3rdPartyInitLoginTestPlan, // oidcc-3rdparty-init-login-certification-test-plan
	OIDCCBackchannelRpInitiatedLogoutTestPlan, // oidcc-backchannel-rp-initiated-logout-certification-test-plan
	OIDCCBasicTestPlan, // oidcc-basic-certification-test-plan
	OIDCCConfigTestPlan, // oidcc-config-certification-test-plan
	OIDCCDynamicTestPlan, // oidcc-dynamic-certification-test-plan
	OIDCCFrontchannelRpInitiatedLogoutTestPlan, // oidcc-frontchannel-rp-initiated-logout-certification-test-plan
	OIDCCRpInitiatedLogoutTestPlan, // oidcc-rp-initiated-logout-certification-test-plan
	OIDCCSessionManagementTestPlan, // oidcc-session-management-certification-test-plan
	OIDCCClient3rdPartyInitiatedLoginTestPlan, // oidcc-client-test-3rd-party-init-login-test-plan
	OIDCCClientBasicTestPlan, // oidcc-client-basic-certification-test-plan
	OIDCCClientDynamicTestPlan, // oidcc-client-dynamic-certification-test-plan
	OIDCCClientBackChannelLogoutRPBasicTestPlan, // oidcc-client-back-channel-logout-rp-basic
	OIDCCClientFrontChannelLogoutRPBasicTestPlan, // oidcc-client-front-channel-logout-rp-basic
	OIDCCClientLogoutTestPlan, // oidcc-client-logout-test-plan
	OIDCCClientRPInitiatedLogoutRPBasicTestPlan, // oidcc-client-rp-initiated-logout-rp-basic
	OIDCCClientSessionManagementRPBasicTestPlan, // oidcc-client-rp-session-management-rp-basic
];

export function findModule(testName: string): TestModuleClass<AbstractTestModule> | undefined {
	return modules.find((m) => m.meta?.testName === testName);
}

export function findPlan(testPlanName: string): TestPlanClass | undefined {
	return plans.find((p) => p.meta.testPlanName === testPlanName);
}
